// FONTE CANÔNICA dos schemas das tools do agente (WF2).
// RUNTIME: o n8n NÃO importa este arquivo — os schemas ficam colados no Code node
// "Build OpenAI Request" do WF2 (cdQwn4joLcuWlTJQ). Ao mudar, edite OS DOIS e mantenha sync.
export const tools = [
  { type: 'function', function: { name: 'buscar_empresa', description: 'Resolve CNPJ para codigo da empresa no SOC.', parameters: { type: 'object', properties: { cnpj: { type: 'string' } }, required: ['cnpj'] } } },
  { type: 'function', function: { name: 'buscar_funcionario', description: 'Verifica se funcionario com este CPF esta ativo no SOC dentro da empresa.', parameters: { type: 'object', properties: { cpf: { type: 'string' }, codigo_empresa: { type: 'integer' } }, required: ['cpf', 'codigo_empresa'] } } },
  { type: 'function', function: { name: 'listar_slots', description: 'Lista horarios disponiveis. O sistema escolhe a agenda certa automaticamente: se funcionario for da New Life usa New Life; senao se cidade for uma das atendidas (Medianeira, Londrina, Santa Helena, Foz do Iguacu) usa a da cidade; senao usa Rede Credenciada.', parameters: { type: 'object', properties: { codigo_empresa: { type: 'integer' }, cpf_funcionario: { type: 'string' }, cidade: { type: 'string' }, tipo_compromisso: { type: 'string', enum: ['PERIODICO','DEMISSIONAL','ADMISSIONAL'] }, data_de: { type: 'string' }, data_ate: { type: 'string' } }, required: ['codigo_empresa','cpf_funcionario','cidade','tipo_compromisso','data_de','data_ate'] } } },
  { type: 'function', function: { name: 'agendar_no_soc', description: 'Realiza o agendamento de fato no SOC. Use APENAS apos o cliente confirmar com SIM via enviar_confirmacao.', parameters: { type: 'object', properties: { codigo_empresa: { type: 'integer' }, cpf_funcionario: { type: 'string' }, cidade: { type: 'string' }, tipo_compromisso: { type: 'string', enum: ['PERIODICO','DEMISSIONAL','ADMISSIONAL'] }, data: { type: 'string', description: 'DD/MM/AAAA' }, hora: { type: 'string', description: 'HH:MM' } }, required: ['codigo_empresa','cpf_funcionario','cidade','tipo_compromisso','data','hora'] } } },
  { type: 'function', function: { name: 'enviar_confirmacao', description: 'Envia resumo final ao cliente e coloca a conversa em aguardando_confirmacao.', parameters: { type: 'object', properties: { resumo: { type: 'string' } }, required: ['resumo'] } } },
  { type: 'function', function: { name: 'enviar_mensagem', description: 'Envia texto livre ao cliente via WhatsApp.', parameters: { type: 'object', properties: { texto: { type: 'string' } }, required: ['texto'] } } },
  { type: 'function', function: { name: 'transferir_humano', description: 'Transfere o atendimento para um humano da equipe Safe SILENCIOSAMENTE. Usar quando: tipo de exame fora do escopo (qualquer um diferente de PERIODICO/DEMISSIONAL/ADMISSIONAL), funcionario nao encontrado no SOC, empresa nao cadastrada, hierarquia (unidade/setor/cargo) nao encontrada, setor/cargo do funcionario divergentes do cadastro SOC, erro no cadastro do funcionario, ou erro grave do SOC. O sistema mandara mensagem padrao. NUNCA mencione ao cliente que voce nao consegue fazer o agendamento.', parameters: { type: 'object', properties: { motivo: { type: 'string', description: 'exame_fora_escopo, funcionario_nao_encontrado, empresa_nao_cadastrada, hierarquia_nao_encontrada, dados_funcionario_divergentes, erro_cadastro_soc, erro_soc, outro' }, contexto: { type: 'object', description: 'Dados coletados ate o momento' } }, required: ['motivo'] } } },
  { type: 'function', function: { name: 'notificar_safe', description: 'Cria notificacao interna para a equipe Safe sem transferir o cliente.', parameters: { type: 'object', properties: { tipo: { type: 'string', enum: ['erro_soc','revisao','outro'] }, prioridade: { type: 'string', enum: ['p0','p1','p2'] }, payload: { type: 'object' } }, required: ['tipo','prioridade'] } } },
  { type: 'function', function: { name: 'validar_hierarquia', description: 'Valida se a tripla unidade+setor+cargo existe na hierarquia da empresa no SOC. Use SOMENTE no fluxo ADMISSIONAL, apos coletar unidade/setor/cargo e ANTES de pedir a data.', parameters: { type: 'object', properties: { codigo_empresa: { type: 'integer' }, unidade: { type: 'string' }, setor: { type: 'string' }, cargo: { type: 'string' } }, required: ['codigo_empresa','unidade','setor','cargo'] } } },
  { type: 'function', function: { name: 'cadastrar_funcionario', description: 'Cadastra funcionario NOVO no SOC (fluxo ADMISSIONAL). Use APENAS apos o cliente confirmar SIM; nunca por iniciativa propria.', parameters: { type: 'object', properties: { codigo_empresa: { type: 'integer' }, cpf: { type: 'string' }, nome: { type: 'string' }, data_nascimento: { type: 'string', description: 'DD/MM/AAAA' }, sexo: { type: 'string', enum: ['MASCULINO','FEMININO'] }, estado_civil: { type: 'string', enum: ['SOLTEIRO','CASADO','SEPARADO','DIVORCIADO','VIUVO','UNIAO_ESTAVEL','OUTROS'] }, ctps: { type: 'object', properties: { nr: { type: 'string' }, serie: { type: 'string' }, uf: { type: 'string' } } }, data_admissao: { type: 'string', description: 'DD/MM/AAAA' }, unidade: { type: 'string' }, setor: { type: 'string' }, cargo: { type: 'string' } }, required: ['codigo_empresa','cpf','nome','data_nascimento','sexo','estado_civil','data_admissao','unidade','setor','cargo'] } } },
];
